################################################################################
#
# Program written in R
# Kevin Williams
# Test version, updated 28 February 2011
#
# 
#
################################################################################
#
# Identifying ID codes of compounds selected by Kurt's process
#
################################################################################
#
# 28 Feb: Wrote it; tested it; finished it. Simples.
# 11 Mar: This version is being used for the first cherrypick simulation
#   and run.
# 17 Mar: Found out that it gives 95 comopunds when asked for 96 - bug found to
#   be due to read.csv(filename,header=TRUE) default (switched to FALSE)
# 05 Apr: Added a routine to provide the compound IDs as a .xml file for feeding
#   back into Eve for the first round of cherrypicking; also added this as a 
#   .txt file as Ron seems to have difficulty with .xml files in his email.
#
################################################################################
#
# Input: Two files - the index output (chosenlist.csv) from Kurt's Octave 
#      code (multiSelOptToFile.m) & the full index/compound list 
#      (all_compounds_indexed.csv) from smiles.r
#
# Main outputs: 
#   1. A table (chosen_compounds.csv) containing the index, the compound ID and
#      the SMILES code   
#   2. A .xml file for feeding back into Eve, containing the compound IDs
#       (as xml_list.xml and xml_list.txt)
#   
################################################################################

chosen_filename <- "chosenlist.csv"
all_compounds_filename <- "all_compounds_indexed.csv"
chosen <- read.csv(chosen_filename,header=FALSE)
all_compounds <- read.csv(all_compounds_filename)
# gets the two sets of data
all_compounds$X <- NULL
# removes data column called X
m <- dim(all_compounds)[1]
n <- dim(chosen)[1]
# identifies the lengths of each list
#
index <- array(1:n)
compid <- array(1:n)
smiles <- array(1:n)

for (i in 1:m){
  for (j in 1:n){
    if (identical(all_compounds[i,1],chosen[j,1])){
       index[j] <- all_compounds[i,1]
       compid[j] <- all_compounds[i,2]
       smiles[j] <- as.character(all_compounds[i,3])
       j <- n
    }
    }
    }
# sorts out all three items of data for each index number generated by Kurt's
#   code
#
chosen_all_data <- data.frame(index,compid,smiles)
write.csv(chosen_all_data,file="chosen_compounds.csv",row.names=FALSE)
# saves the output, ready for the cherry-picking phase
#
# next bit: write an .xml file of the format:
#   <compounds>
#   <compound><id>9079</id></compound>
#   <compound><id>16499</id></compound>
#   <compound><id>12103</id></compound>
#   <compound><id>9614</id></compound>
#   <compound><id>10280</id></compound>
#   <compound><id>6602</id></compound>
#   <compound><id>10023</id></compound>
#   </compounds>
# 
# with a filename in the format:
#
#   CP_77_YYYYMMDDHHMMSS.XML
#   (CP = cherry pick, investigation ID = 77, timestamp of when created)
#
n <- dim(compid)

xml_list <- array(1:(n+2))
xml_list[1] <- "<compounds>"
xml_list[n+2] <- "</compounds>"

for (i in 1:n){
  xml_list[i+1] <- paste("<compound><id>",compid[i],"</id></compound>",sep="")
  }
write.table(data.matrix(xml_list),"xml_list.xml",quote=FALSE,
                sep=",",col.names=FALSE,row.names=FALSE)
write.table(data.matrix(xml_list),"xml_list.txt",quote=FALSE,
                sep=",",col.names=FALSE,row.names=FALSE)
